/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IERC777ProxyContract
  extends Truffle.Contract<IERC777ProxyInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<IERC777ProxyInstance>;
}

type AllEvents = never;

export interface IERC777ProxyInstance extends Truffle.ContractInstance {
  underlying(txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    underlying(txDetails?: Truffle.TransactionDetails): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
