/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { AccessControlContract } from "./AccessControl";
import { AccessControlEnumerableContract } from "./AccessControlEnumerable";
import { ERC165Contract } from "./ERC165";
import { ERC777Contract } from "./ERC777";
import { ERC777PresetFixedSupplyContract } from "./ERC777PresetFixedSupply";
import { IAccessControlContract } from "./IAccessControl";
import { IAccessControlEnumerableContract } from "./IAccessControlEnumerable";
import { IERC165Contract } from "./IERC165";
import { IERC1820RegistryContract } from "./IERC1820Registry";
import { IERC20Contract } from "./IERC20";
import { IERC20MetadataContract } from "./IERC20Metadata";
import { IERC777Contract } from "./IERC777";
import { IERC777RecipientContract } from "./IERC777Recipient";
import { IERC777SenderContract } from "./IERC777Sender";
import { LockableContract } from "./Lockable";
import { LockedUltimateChampionsTokenContract } from "./LockedUltimateChampionsToken";
import { MigrationsContract } from "./Migrations";
import { MulticallContract } from "./Multicall";
import { OwnableContract } from "./Ownable";
import { PausableContract } from "./Pausable";
import { PaymentSplitterContract } from "./PaymentSplitter";
import { TestLockableContract } from "./TestLockable";
import { UltimateChampionsTokenContract } from "./UltimateChampionsToken";
import { UPaymentSplitterContract } from "./UPaymentSplitter";
import { VestingWalletContract } from "./VestingWallet";
import { VestingWalletMultiLinearContract } from "./VestingWalletMultiLinear";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AccessControl"): AccessControlContract;
      require(name: "AccessControlEnumerable"): AccessControlEnumerableContract;
      require(name: "ERC165"): ERC165Contract;
      require(name: "ERC777"): ERC777Contract;
      require(name: "ERC777PresetFixedSupply"): ERC777PresetFixedSupplyContract;
      require(name: "IAccessControl"): IAccessControlContract;
      require(
        name: "IAccessControlEnumerable"
      ): IAccessControlEnumerableContract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC1820Registry"): IERC1820RegistryContract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "IERC777"): IERC777Contract;
      require(name: "IERC777Recipient"): IERC777RecipientContract;
      require(name: "IERC777Sender"): IERC777SenderContract;
      require(name: "Lockable"): LockableContract;
      require(
        name: "LockedUltimateChampionsToken"
      ): LockedUltimateChampionsTokenContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "Multicall"): MulticallContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "Pausable"): PausableContract;
      require(name: "PaymentSplitter"): PaymentSplitterContract;
      require(name: "TestLockable"): TestLockableContract;
      require(name: "UltimateChampionsToken"): UltimateChampionsTokenContract;
      require(name: "UPaymentSplitter"): UPaymentSplitterContract;
      require(name: "VestingWallet"): VestingWalletContract;
      require(
        name: "VestingWalletMultiLinear"
      ): VestingWalletMultiLinearContract;
    }
  }
}

export { AccessControlContract, AccessControlInstance } from "./AccessControl";
export {
  AccessControlEnumerableContract,
  AccessControlEnumerableInstance,
} from "./AccessControlEnumerable";
export { ERC165Contract, ERC165Instance } from "./ERC165";
export { ERC777Contract, ERC777Instance } from "./ERC777";
export {
  ERC777PresetFixedSupplyContract,
  ERC777PresetFixedSupplyInstance,
} from "./ERC777PresetFixedSupply";
export {
  IAccessControlContract,
  IAccessControlInstance,
} from "./IAccessControl";
export {
  IAccessControlEnumerableContract,
  IAccessControlEnumerableInstance,
} from "./IAccessControlEnumerable";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export {
  IERC1820RegistryContract,
  IERC1820RegistryInstance,
} from "./IERC1820Registry";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  IERC20MetadataContract,
  IERC20MetadataInstance,
} from "./IERC20Metadata";
export { IERC777Contract, IERC777Instance } from "./IERC777";
export {
  IERC777RecipientContract,
  IERC777RecipientInstance,
} from "./IERC777Recipient";
export { IERC777SenderContract, IERC777SenderInstance } from "./IERC777Sender";
export { LockableContract, LockableInstance } from "./Lockable";
export {
  LockedUltimateChampionsTokenContract,
  LockedUltimateChampionsTokenInstance,
} from "./LockedUltimateChampionsToken";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { MulticallContract, MulticallInstance } from "./Multicall";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { PausableContract, PausableInstance } from "./Pausable";
export {
  PaymentSplitterContract,
  PaymentSplitterInstance,
} from "./PaymentSplitter";
export { TestLockableContract, TestLockableInstance } from "./TestLockable";
export {
  UltimateChampionsTokenContract,
  UltimateChampionsTokenInstance,
} from "./UltimateChampionsToken";
export {
  UPaymentSplitterContract,
  UPaymentSplitterInstance,
} from "./UPaymentSplitter";
export { VestingWalletContract, VestingWalletInstance } from "./VestingWallet";
export {
  VestingWalletMultiLinearContract,
  VestingWalletMultiLinearInstance,
} from "./VestingWalletMultiLinear";
