/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface TestPaymentRelayV0Contract
  extends Truffle.Contract<TestPaymentRelayV0Instance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<TestPaymentRelayV0Instance>;
}

type AllEvents = never;

export interface TestPaymentRelayV0Instance extends Truffle.ContractInstance {
  getPayment(
    UID: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: string; 1: BN }>;

  methods: {
    getPayment(
      UID: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: string; 1: BN }>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
