/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface TimelockControllerContract
  extends Truffle.Contract<TimelockControllerInstance> {
  "new"(
    minDelay: number | BN | string,
    proposers: string[],
    executors: string[],
    meta?: Truffle.TransactionDetails
  ): Promise<TimelockControllerInstance>;
}

export interface CallExecuted {
  name: "CallExecuted";
  args: {
    id: string;
    index: BN;
    target: string;
    value: BN;
    data: string;
    0: string;
    1: BN;
    2: string;
    3: BN;
    4: string;
  };
}

export interface CallScheduled {
  name: "CallScheduled";
  args: {
    id: string;
    index: BN;
    target: string;
    value: BN;
    data: string;
    predecessor: string;
    delay: BN;
    0: string;
    1: BN;
    2: string;
    3: BN;
    4: string;
    5: string;
    6: BN;
  };
}

export interface Cancelled {
  name: "Cancelled";
  args: {
    id: string;
    0: string;
  };
}

export interface MinDelayChange {
  name: "MinDelayChange";
  args: {
    oldDuration: BN;
    newDuration: BN;
    0: BN;
    1: BN;
  };
}

export interface RoleAdminChanged {
  name: "RoleAdminChanged";
  args: {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
    0: string;
    1: string;
    2: string;
  };
}

export interface RoleGranted {
  name: "RoleGranted";
  args: {
    role: string;
    account: string;
    sender: string;
    0: string;
    1: string;
    2: string;
  };
}

export interface RoleRevoked {
  name: "RoleRevoked";
  args: {
    role: string;
    account: string;
    sender: string;
    0: string;
    1: string;
    2: string;
  };
}

type AllEvents =
  | CallExecuted
  | CallScheduled
  | Cancelled
  | MinDelayChange
  | RoleAdminChanged
  | RoleGranted
  | RoleRevoked;

export interface TimelockControllerInstance extends Truffle.ContractInstance {
  DEFAULT_ADMIN_ROLE(txDetails?: Truffle.TransactionDetails): Promise<string>;

  EXECUTOR_ROLE(txDetails?: Truffle.TransactionDetails): Promise<string>;

  PROPOSER_ROLE(txDetails?: Truffle.TransactionDetails): Promise<string>;

  TIMELOCK_ADMIN_ROLE(txDetails?: Truffle.TransactionDetails): Promise<string>;

  /**
   * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
   */
  getRoleAdmin(
    role: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  /**
   * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
   */
  grantRole: {
    (
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Returns `true` if `account` has been granted `role`.
   */
  hasRole(
    role: string,
    account: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  /**
   * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been revoked `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
   */
  renounceRole: {
    (
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
   */
  revokeRole: {
    (
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * See {IERC165-supportsInterface}.
   */
  supportsInterface(
    interfaceId: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  /**
   * Returns whether an id correspond to a registered operation. This includes both Pending, Ready and Done operations.
   */
  isOperation(
    id: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  /**
   * Returns whether an operation is pending or not.
   */
  isOperationPending(
    id: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  /**
   * Returns whether an operation is ready or not.
   */
  isOperationReady(
    id: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  /**
   * Returns whether an operation is done or not.
   */
  isOperationDone(
    id: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  /**
   * Returns the timestamp at with an operation becomes ready (0 for unset operations, 1 for done operations).
   */
  getTimestamp(id: string, txDetails?: Truffle.TransactionDetails): Promise<BN>;

  /**
   * Returns the minimum delay for an operation to become valid. This value can be changed by executing an operation that calls `updateDelay`.
   */
  getMinDelay(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  /**
   * Returns the identifier of an operation containing a single transaction.
   */
  hashOperation(
    target: string,
    value: number | BN | string,
    data: string,
    predecessor: string,
    salt: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  /**
   * Returns the identifier of an operation containing a batch of transactions.
   */
  hashOperationBatch(
    targets: string[],
    values: (number | BN | string)[],
    datas: string[],
    predecessor: string,
    salt: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  /**
   * Schedule an operation containing a single transaction. Emits a {CallScheduled} event. Requirements: - the caller must have the 'proposer' role.
   */
  schedule: {
    (
      target: string,
      value: number | BN | string,
      data: string,
      predecessor: string,
      salt: string,
      delay: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      target: string,
      value: number | BN | string,
      data: string,
      predecessor: string,
      salt: string,
      delay: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      target: string,
      value: number | BN | string,
      data: string,
      predecessor: string,
      salt: string,
      delay: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      target: string,
      value: number | BN | string,
      data: string,
      predecessor: string,
      salt: string,
      delay: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Schedule an operation containing a batch of transactions. Emits one {CallScheduled} event per transaction in the batch. Requirements: - the caller must have the 'proposer' role.
   */
  scheduleBatch: {
    (
      targets: string[],
      values: (number | BN | string)[],
      datas: string[],
      predecessor: string,
      salt: string,
      delay: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      targets: string[],
      values: (number | BN | string)[],
      datas: string[],
      predecessor: string,
      salt: string,
      delay: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      targets: string[],
      values: (number | BN | string)[],
      datas: string[],
      predecessor: string,
      salt: string,
      delay: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      targets: string[],
      values: (number | BN | string)[],
      datas: string[],
      predecessor: string,
      salt: string,
      delay: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Cancel an operation. Requirements: - the caller must have the 'proposer' role.
   */
  cancel: {
    (id: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(id: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      id: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      id: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Execute an (ready) operation containing a single transaction. Emits a {CallExecuted} event. Requirements: - the caller must have the 'executor' role.
   */
  execute: {
    (
      target: string,
      value: number | BN | string,
      data: string,
      predecessor: string,
      salt: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      target: string,
      value: number | BN | string,
      data: string,
      predecessor: string,
      salt: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      target: string,
      value: number | BN | string,
      data: string,
      predecessor: string,
      salt: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      target: string,
      value: number | BN | string,
      data: string,
      predecessor: string,
      salt: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Execute an (ready) operation containing a batch of transactions. Emits one {CallExecuted} event per transaction in the batch. Requirements: - the caller must have the 'executor' role.
   */
  executeBatch: {
    (
      targets: string[],
      values: (number | BN | string)[],
      datas: string[],
      predecessor: string,
      salt: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      targets: string[],
      values: (number | BN | string)[],
      datas: string[],
      predecessor: string,
      salt: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      targets: string[],
      values: (number | BN | string)[],
      datas: string[],
      predecessor: string,
      salt: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      targets: string[],
      values: (number | BN | string)[],
      datas: string[],
      predecessor: string,
      salt: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Changes the minimum timelock duration for future operations. Emits a {MinDelayChange} event. Requirements: - the caller must be the timelock itself. This can only be achieved by scheduling and later executing an operation where the timelock is the target and the data is the ABI-encoded call to this function.
   */
  updateDelay: {
    (
      newDelay: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      newDelay: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      newDelay: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      newDelay: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    DEFAULT_ADMIN_ROLE(txDetails?: Truffle.TransactionDetails): Promise<string>;

    EXECUTOR_ROLE(txDetails?: Truffle.TransactionDetails): Promise<string>;

    PROPOSER_ROLE(txDetails?: Truffle.TransactionDetails): Promise<string>;

    TIMELOCK_ADMIN_ROLE(
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    /**
     * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
     */
    getRoleAdmin(
      role: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    /**
     * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
     */
    grantRole: {
      (
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Returns `true` if `account` has been granted `role`.
     */
    hasRole(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    /**
     * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been revoked `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
     */
    renounceRole: {
      (
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
     */
    revokeRole: {
      (
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * See {IERC165-supportsInterface}.
     */
    supportsInterface(
      interfaceId: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    /**
     * Returns whether an id correspond to a registered operation. This includes both Pending, Ready and Done operations.
     */
    isOperation(
      id: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    /**
     * Returns whether an operation is pending or not.
     */
    isOperationPending(
      id: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    /**
     * Returns whether an operation is ready or not.
     */
    isOperationReady(
      id: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    /**
     * Returns whether an operation is done or not.
     */
    isOperationDone(
      id: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    /**
     * Returns the timestamp at with an operation becomes ready (0 for unset operations, 1 for done operations).
     */
    getTimestamp(
      id: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    /**
     * Returns the minimum delay for an operation to become valid. This value can be changed by executing an operation that calls `updateDelay`.
     */
    getMinDelay(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    /**
     * Returns the identifier of an operation containing a single transaction.
     */
    hashOperation(
      target: string,
      value: number | BN | string,
      data: string,
      predecessor: string,
      salt: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    /**
     * Returns the identifier of an operation containing a batch of transactions.
     */
    hashOperationBatch(
      targets: string[],
      values: (number | BN | string)[],
      datas: string[],
      predecessor: string,
      salt: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    /**
     * Schedule an operation containing a single transaction. Emits a {CallScheduled} event. Requirements: - the caller must have the 'proposer' role.
     */
    schedule: {
      (
        target: string,
        value: number | BN | string,
        data: string,
        predecessor: string,
        salt: string,
        delay: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        target: string,
        value: number | BN | string,
        data: string,
        predecessor: string,
        salt: string,
        delay: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        target: string,
        value: number | BN | string,
        data: string,
        predecessor: string,
        salt: string,
        delay: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        target: string,
        value: number | BN | string,
        data: string,
        predecessor: string,
        salt: string,
        delay: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Schedule an operation containing a batch of transactions. Emits one {CallScheduled} event per transaction in the batch. Requirements: - the caller must have the 'proposer' role.
     */
    scheduleBatch: {
      (
        targets: string[],
        values: (number | BN | string)[],
        datas: string[],
        predecessor: string,
        salt: string,
        delay: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        targets: string[],
        values: (number | BN | string)[],
        datas: string[],
        predecessor: string,
        salt: string,
        delay: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        targets: string[],
        values: (number | BN | string)[],
        datas: string[],
        predecessor: string,
        salt: string,
        delay: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        targets: string[],
        values: (number | BN | string)[],
        datas: string[],
        predecessor: string,
        salt: string,
        delay: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Cancel an operation. Requirements: - the caller must have the 'proposer' role.
     */
    cancel: {
      (id: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(id: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(
        id: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        id: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Execute an (ready) operation containing a single transaction. Emits a {CallExecuted} event. Requirements: - the caller must have the 'executor' role.
     */
    execute: {
      (
        target: string,
        value: number | BN | string,
        data: string,
        predecessor: string,
        salt: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        target: string,
        value: number | BN | string,
        data: string,
        predecessor: string,
        salt: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        target: string,
        value: number | BN | string,
        data: string,
        predecessor: string,
        salt: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        target: string,
        value: number | BN | string,
        data: string,
        predecessor: string,
        salt: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Execute an (ready) operation containing a batch of transactions. Emits one {CallExecuted} event per transaction in the batch. Requirements: - the caller must have the 'executor' role.
     */
    executeBatch: {
      (
        targets: string[],
        values: (number | BN | string)[],
        datas: string[],
        predecessor: string,
        salt: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        targets: string[],
        values: (number | BN | string)[],
        datas: string[],
        predecessor: string,
        salt: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        targets: string[],
        values: (number | BN | string)[],
        datas: string[],
        predecessor: string,
        salt: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        targets: string[],
        values: (number | BN | string)[],
        datas: string[],
        predecessor: string,
        salt: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Changes the minimum timelock duration for future operations. Emits a {MinDelayChange} event. Requirements: - the caller must be the timelock itself. This can only be achieved by scheduling and later executing an operation where the timelock is the target and the data is the ABI-encoded call to this function.
     */
    updateDelay: {
      (
        newDelay: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        newDelay: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        newDelay: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        newDelay: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
