/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface TokenTransferRelayContract
  extends Truffle.Contract<TokenTransferRelayInstance> {
  "new"(
    _erc721: string,
    _erc20: string,
    _erc721Receiver: string,
    _erc20Receiver: string,
    meta?: Truffle.TransactionDetails
  ): Promise<TokenTransferRelayInstance>;
}

export interface RoleAdminChanged {
  name: "RoleAdminChanged";
  args: {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
    0: string;
    1: string;
    2: string;
  };
}

export interface RoleGranted {
  name: "RoleGranted";
  args: {
    role: string;
    account: string;
    sender: string;
    0: string;
    1: string;
    2: string;
  };
}

export interface RoleRevoked {
  name: "RoleRevoked";
  args: {
    role: string;
    account: string;
    sender: string;
    0: string;
    1: string;
    2: string;
  };
}

export interface TransferExecuted {
  name: "TransferExecuted";
  args: {
    UID: string;
    0: string;
  };
}

export interface TransferReserved {
  name: "TransferReserved";
  args: {
    UID: string;
    from: string;
    tokenIds: BN[];
    amount: BN;
    0: string;
    1: string;
    2: BN[];
    3: BN;
  };
}

export interface TransferReverted {
  name: "TransferReverted";
  args: {
    UID: string;
    0: string;
  };
}

type AllEvents =
  | RoleAdminChanged
  | RoleGranted
  | RoleRevoked
  | TransferExecuted
  | TransferReserved
  | TransferReverted;

export interface TokenTransferRelayInstance extends Truffle.ContractInstance {
  DEFAULT_ADMIN_ROLE(txDetails?: Truffle.TransactionDetails): Promise<string>;

  ERC20Origin(txDetails?: Truffle.TransactionDetails): Promise<string>;

  ERC20Receiver(txDetails?: Truffle.TransactionDetails): Promise<string>;

  ERC721Origin(txDetails?: Truffle.TransactionDetails): Promise<string>;

  ERC721Receiver(txDetails?: Truffle.TransactionDetails): Promise<string>;

  MAINTENANCE_ROLE(txDetails?: Truffle.TransactionDetails): Promise<string>;

  OPERATOR_ROLE(txDetails?: Truffle.TransactionDetails): Promise<string>;

  RECEIVER_ROLE(txDetails?: Truffle.TransactionDetails): Promise<string>;

  TRANSFER_EXECUTED(txDetails?: Truffle.TransactionDetails): Promise<string>;

  TRANSFER_RESERVED(txDetails?: Truffle.TransactionDetails): Promise<string>;

  TRANSFER_REVERTED(txDetails?: Truffle.TransactionDetails): Promise<string>;

  /**
   * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
   */
  getRoleAdmin(
    role: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  /**
   * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
   */
  grantRole: {
    (
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Returns `true` if `account` has been granted `role`.
   */
  hasRole(
    role: string,
    account: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  /**
   * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been revoked `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
   */
  renounceRole: {
    (
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
   */
  revokeRole: {
    (
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * See {IERC165-supportsInterface}.
   */
  supportsInterface(
    interfaceId: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  /**
   * See {IERC721Receiver-onERC721Received}.
   */
  onERC721Received(
    operator: string,
    from: string,
    tokenId: number | BN | string,
    data: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  /**
   * sets the address to which ERC20 tokens should be sent to. The function caller must have been granted MAINTENANCE_ROLE.
   */
  setERC721Receiver: {
    (_erc721Receiver: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _erc721Receiver: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _erc721Receiver: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _erc721Receiver: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * sets the address to which ERC721 tokens should be sent to. The function caller must have been granted MAINTENANCE_ROLE.
   */
  setERC20Receiver: {
    (_erc20Receiver: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _erc20Receiver: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _erc20Receiver: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _erc20Receiver: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  getTransfer(
    UID: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ from: string; tokenIds: BN[]; amount: BN; state: string }>;

  isTransferReserved(
    UID: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  isTransferProcessed(
    UID: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  /**
   * Function transfers `tokenIds` and `amount` of erc20 to the contract's account. A new Payment instance holding the payment details is assigned to `UID`. Transfer intent is placed in TRANSFER_RESERVED state. Requirements: - `tokenIds` must contain at least 1 token ID - `amount` must be greater than 0 - reserved transfer must not exist for given `UID` - processed transfer must not exist for given `UID`
   * Reserves a token transfer on behalf of a NFCHAMP/CHAMP holder, placing the holder's tokens under escrow.
   */
  reserveTransfer: {
    (
      UID: string,
      from: string,
      tokenIds: (number | BN | string)[],
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      UID: string,
      from: string,
      tokenIds: (number | BN | string)[],
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      UID: string,
      from: string,
      tokenIds: (number | BN | string)[],
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      UID: string,
      from: string,
      tokenIds: (number | BN | string)[],
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  executeTransfer: {
    (UID: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(UID: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      UID: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      UID: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  revertTransfer: {
    (UID: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(UID: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      UID: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      UID: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    DEFAULT_ADMIN_ROLE(txDetails?: Truffle.TransactionDetails): Promise<string>;

    ERC20Origin(txDetails?: Truffle.TransactionDetails): Promise<string>;

    ERC20Receiver(txDetails?: Truffle.TransactionDetails): Promise<string>;

    ERC721Origin(txDetails?: Truffle.TransactionDetails): Promise<string>;

    ERC721Receiver(txDetails?: Truffle.TransactionDetails): Promise<string>;

    MAINTENANCE_ROLE(txDetails?: Truffle.TransactionDetails): Promise<string>;

    OPERATOR_ROLE(txDetails?: Truffle.TransactionDetails): Promise<string>;

    RECEIVER_ROLE(txDetails?: Truffle.TransactionDetails): Promise<string>;

    TRANSFER_EXECUTED(txDetails?: Truffle.TransactionDetails): Promise<string>;

    TRANSFER_RESERVED(txDetails?: Truffle.TransactionDetails): Promise<string>;

    TRANSFER_REVERTED(txDetails?: Truffle.TransactionDetails): Promise<string>;

    /**
     * Returns the admin role that controls `role`. See {grantRole} and {revokeRole}. To change a role's admin, use {_setRoleAdmin}.
     */
    getRoleAdmin(
      role: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    /**
     * Grants `role` to `account`. If `account` had not been already granted `role`, emits a {RoleGranted} event. Requirements: - the caller must have ``role``'s admin role.
     */
    grantRole: {
      (
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Returns `true` if `account` has been granted `role`.
     */
    hasRole(
      role: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    /**
     * Revokes `role` from the calling account. Roles are often managed via {grantRole} and {revokeRole}: this function's purpose is to provide a mechanism for accounts to lose their privileges if they are compromised (such as when a trusted device is misplaced). If the calling account had been revoked `role`, emits a {RoleRevoked} event. Requirements: - the caller must be `account`.
     */
    renounceRole: {
      (
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Revokes `role` from `account`. If `account` had been granted `role`, emits a {RoleRevoked} event. Requirements: - the caller must have ``role``'s admin role.
     */
    revokeRole: {
      (
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        role: string,
        account: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * See {IERC165-supportsInterface}.
     */
    supportsInterface(
      interfaceId: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    /**
     * See {IERC721Receiver-onERC721Received}.
     */
    onERC721Received(
      operator: string,
      from: string,
      tokenId: number | BN | string,
      data: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    /**
     * sets the address to which ERC20 tokens should be sent to. The function caller must have been granted MAINTENANCE_ROLE.
     */
    setERC721Receiver: {
      (
        _erc721Receiver: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _erc721Receiver: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _erc721Receiver: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _erc721Receiver: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * sets the address to which ERC721 tokens should be sent to. The function caller must have been granted MAINTENANCE_ROLE.
     */
    setERC20Receiver: {
      (_erc20Receiver: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _erc20Receiver: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _erc20Receiver: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _erc20Receiver: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    getTransfer(
      UID: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ from: string; tokenIds: BN[]; amount: BN; state: string }>;

    isTransferReserved(
      UID: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    isTransferProcessed(
      UID: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    /**
     * Function transfers `tokenIds` and `amount` of erc20 to the contract's account. A new Payment instance holding the payment details is assigned to `UID`. Transfer intent is placed in TRANSFER_RESERVED state. Requirements: - `tokenIds` must contain at least 1 token ID - `amount` must be greater than 0 - reserved transfer must not exist for given `UID` - processed transfer must not exist for given `UID`
     * Reserves a token transfer on behalf of a NFCHAMP/CHAMP holder, placing the holder's tokens under escrow.
     */
    reserveTransfer: {
      (
        UID: string,
        from: string,
        tokenIds: (number | BN | string)[],
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        UID: string,
        from: string,
        tokenIds: (number | BN | string)[],
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        UID: string,
        from: string,
        tokenIds: (number | BN | string)[],
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        UID: string,
        from: string,
        tokenIds: (number | BN | string)[],
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    executeTransfer: {
      (UID: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(UID: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(
        UID: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        UID: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    revertTransfer: {
      (UID: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(UID: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(
        UID: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        UID: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
